In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [29]:
pcos_data = pd.read_csv('pcos_data.csv')

In [30]:
pcos_data.head()

,PCOS,Age,Weight,Height,BMI,Blood_Group,Pulse_rate,RR,Hb,Cycle,...,Waist_Hip_Ratio,Weight_gain,hair_growth,Skin_darkening,Hair_loss,Pimples,Fast_food,Reg_Exercise,BP_Systolic,BP_Diastolic
0,0,28,44.6,152.0,19.3,15,78,22,10.48,2,...,0.83,0,0,0,0,0,1,0,110,80
1,0,36,65.0,161.5,24.9,15,74,20,11.70,2,...,0.84,0,0,0,0,0,0,0,120,70
2,1,33,68.8,165.0,25.3,11,72,18,11.80,2,...,0.90,0,0,0,1,1,1,0,120,80
3,1,27,45.0,158.0,18.0,14,72,20,11.20,2,...,0.89,0,0,1,0,0,1,1,120,80
4,1,27,45.0,158.0,18.0,14,72,20,11.20,2,...,0.89,0,0,1,0,0,1,1,120,80

In [31]:
pcos_data.tail()

,PCOS,Age,Weight,Height,BMI,Blood_Group,Pulse_rate,RR,Hb,Cycle,...,Waist_Hip_Ratio,Weight_gain,hair_growth,Skin_darkening,Hair_loss,Pimples,Fast_food,Reg_Exercise,BP_Systolic,BP_Diastolic
195,1,35,60.0,153.4,25.5,13,72,20,13.2,4,...,0.92,1,0,1,1,1,1,0,120,80
196,1,35,56.0,156.0,23.0,14,73,18,12.1,2,...,0.89,1,1,0,1,1,1,1,120,80
197,0,28,70.0,158.0,28.0,15,72,18,12.0,2,...,0.90,1,1,0,1,0,1,0,110,80
198,0,32,49.0,154.0,20.7,11,72,20,11.2,2,...,0.91,0,0,0,1,1,1,0,110,70
199,1,25,58.0,160.0,22.7,15,74,18,11.9,4,...,0.95,1,1,1,1,0,1,0,110,80

In [32]:
pcos_data.shape

(200, 26)

In [33]:
pcos_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   PCOS             200 non-null    int64
 1   Age              200 non-null    int64
 2   Weight           200 non-null    float64
 3   Height           200 non-null    float64
 4   BMI              200 non-null    float64
 5   Blood_Group      200 non-null    int64
 6   Pulse_rate       200 non-null    int64
 7   RR               200 non-null    int64
 8   Hb               200 non-null    float64
 9   Cycle            200 non-null    int64
 10  Cycle_length     200 non-null    int64
 11  Marriage_Status  200 non-null    float64
 12  Pregnant         200 non-null    int64
 13  No_of_abortions  200 non-null    int64
 14  Hip              200 non-null    int64
 15  Waist            200 non-null    int64
 16  Waist_Hip_Ratio  200 non-null    float64
 17  Weight_gain      200 non-null    int64
 18  hair_growth      200 non-null    int64
 19  Skin_darkening   200 non-null    int64
 20  Hair_loss        200 non-null    int64
 21  Pimples          200 non-null    int64
 22  Fast_food        200 non-null    int64
 23  Reg_Exercise     200 non-null    int64
 24  BP_Systolic      200 non-null    int64
 25  BP_Diastolic     200 non-null    int64
dtypes: float64(6), int64(20)
memory usage: 40.8 KB

In [34]:
pcos_data.isnull().sum()

PCOS               0
Age                0
Weight             0
Height             0
BMI                0
Blood_Group        0
Pulse_rate         0
RR                 0
Hb                 0
Cycle              0
Cycle_length       0
Marriage_Status    0
Pregnant           0
No_of_abortions    0
Hip                0
Waist              0
Waist_Hip_Ratio    0
Weight_gain        0
hair_growth        0
Skin_darkening     0
Hair_loss          0
Pimples            0
Fast_food          0
Reg_Exercise       0
BP_Systolic        0
BP_Diastolic       0
dtype: int64

In [35]:
pcos_data.describe()

,PCOS,Age,Weight,Height,BMI,Blood_Group,Pulse_rate,RR,Hb,Cycle,...,Waist_Hip_Ratio,Weight_gain,hair_growth,Skin_darkening,Hair_loss,Pimples,Fast_food,Reg_Exercise,BP_Systolic,BP_Diastolic
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,...,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000,200.00000,200.000000,200.000000,200.000000
mean,0.440000,30.085000,60.594000,156.978500,24.563000,13.735000,73.555000,19.105000,11.186850,2.560000,...,0.856000,0.395000,0.32500,0.420000,0.405000,0.390000,0.50500,0.310000,113.860000,76.800000
std,0.497633,4.998269,10.699874,6.408207,3.947346,1.811403,2.602082,1.800049,0.786174,0.900251,...,0.039277,0.490077,0.46955,0.494797,0.492124,0.488974,0.50123,0.463654,9.384066,4.782716
min,0.000000,20.000000,33.000000,137.000000,13.400000,11.000000,70.000000,16.000000,8.500000,2.000000,...,0.760000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,12.000000,60.000000
25%,0.000000,27.000000,54.000000,152.000000,21.600000,13.000000,72.000000,18.000000,10.800000,2.000000,...,0.830000,0.000000,0.00000,0.000000,0.000000,0.000000,0.00000,0.000000,110.000000,70.000000
50%,0.000000,29.000000,60.000000,156.000000,24.750000,14.000000,72.000000,18.000000,11.100000,2.000000,...,0.850000,0.000000,0.00000,0.000000,0.000000,0.000000,1.00000,0.000000,110.000000,80.000000
75%,1.000000,34.000000,68.000000,160.000000,26.800000,15.000000,74.000000,20.000000,11.500000,4.000000,...,0.890000,1.000000,1.00000,1.000000,1.000000,1.000000,1.00000,1.000000,120.000000,80.000000
max,1.000000,44.000000,91.400000,180.000000,38.500000,17.000000,80.000000,26.000000,13.800000,4.000000,...,0.980000,1.000000,1.00000,1.000000,1.000000,1.000000,1.00000,1.000000,140.000000,80.000000

In [36]:
pcos_data['PCOS'].value_counts()

PCOS
0    112
1     88
Name: count, dtype: int64

In [37]:
X = pcos_data.drop(columns='PCOS', axis=1)
Y = pcos_data['PCOS']

In [38]:
print(X)

     Age  Weight  Height   BMI  Blood_Group  Pulse_rate  RR     Hb  Cycle  \
0     28    44.6   152.0  19.3           15          78  22  10.48      2
1     36    65.0   161.5  24.9           15          74  20  11.70      2
2     33    68.8   165.0  25.3           11          72  18  11.80      2
3     27    45.0   158.0  18.0           14          72  20  11.20      2
4     27    45.0   158.0  18.0           14          72  20  11.20      2
..   ...     ...     ...   ...          ...         ...  ..    ...    ...
195   35    60.0   153.4  25.5           13          72  20  13.20      4
196   35    56.0   156.0  23.0           14          73  18  12.10      2
197   28    70.0   158.0  28.0           15          72  18  12.00      2
198   32    49.0   154.0  20.7           11          72  20  11.20      2
199   25    58.0   160.0  22.7           15          74  18  11.90      4

     Cycle_length  ...  Waist_Hip_Ratio  Weight_gain  hair_growth  \
0               5  ...             0.83            0            0
1               5  ...             0.84            0            0
2               5  ...             0.90            0            0
3               5  ...             0.89            0            0
4               5  ...             0.89            0            0
..            ...  ...              ...          ...          ...
195             4  ...             0.92            1            0
196             4  ...             0.89            1            1
197             5  ...             0.90            1            1
198             5  ...             0.91            0            0
199             3  ...             0.95            1            1

     Skin_darkening  Hair_loss  Pimples  Fast_food  Reg_Exercise  BP_Systolic  \
0                 0          0        0          1             0          110
1                 0          0        0          0             0          120
2                 0          1        1          1             0          120
3                 1          0        0          1             1          120
4                 1          0        0          1             1          120
..              ...        ...      ...        ...           ...          ...
195               1          1        1          1             0          120
196               0          1        1          1             1          120
197               0          1        0          1             0          110
198               0          1        1          1             0          110
199               1          1        0          1             0          110

     BP_Diastolic
0              80
1              70
2              80
3              80
4              80
..            ...
195            80
196            80
197            80
198            70
199            80

[200 rows x 25 columns]

In [39]:
print(Y)

0      0
1      0
2      1
3      1
4      1
      ..
195    1
196    1
197    0
198    0
199    1
Name: PCOS, Length: 200, dtype: int64

In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [41]:
print(X.shape, X_train.shape, X_test.shape)

(200, 25) (160, 25) (40, 25)

In [42]:
model = LogisticRegression()

In [43]:
model.fit(X_train, Y_train)

c:\Users\Jatin Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [44]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [45]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9375

In [46]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [47]:
print('Accuracy on Test data : ', test_data_accuracy)

Accuracy on Test data :  0.925

In [48]:
input_data = (25, 64, 156, 26.3, 11, 70, 18, 11.2, 2, 6, 6,0, 0, 39, 34, 0.87, 0, 0, 0, 0, 0, 0, 0, 110, 80 )

In [49]:
input_data_as_numpy_array= np.asarray(input_data)

In [50]:
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

In [51]:
prediction = model.predict(input_data_reshaped)
print(prediction)

[0]

c:\Users\Jatin Garg\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [52]:
if prediction[0]== 0:
    print('The Person does not have a PCOS Disease')
else:
    print('The Person has PCOS Disease')

The Person does not have a PCOS Disease

In [53]:
import joblib

filename = '../data_model.pkl'
joblib.dump(model, filename)
print(f"Model saved as {filename}")

Model saved as ../data_model.pkl